# Generated by Django 4.2.7 on 2023-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
